package co.ara.onboarding.platform.storage;

import java.io.InputStream;

/**
 * Where document bytes live. Two adapters, one contract (BlobStoreContract).
 *
 * THERE IS NO delete, AND THAT IS THE DESIGN (spec 7.1). Business records are
 * never deleted -- the database enforces it by withholding the DELETE grant, and
 * this interface states the same thing for bytes by simply not offering the
 * operation. Retiring a document keeps its blob. A delete path belongs with QA
 * Q11's retention rules, designed alongside them, not added here as an unused
 * method someone later finds convenient.
 *
 * Keys are OPAQUE and generated by the adapter. Callers never construct one and
 * never parse one; nothing a user supplied may reach a path or an object name.
 */
public interface BlobStore {

    /**
     * Takes ownership of {@code content} and closes it, whether the write succeeds
     * or fails -- callers must not close it themselves and must not reuse it after
     * this call. This is what lets a real upload stream (a servlet/multipart body,
     * Task 15) be handed straight to {@code put} without leaking a file descriptor
     * per call.
     *
     * @param sizeBytes the caller's declared length. Adapters may use it to choose
     *                  a transfer strategy but must not trust it for correctness.
     * @return the generated storage key, to be persisted on document_version.
     */
    String put(InputStream content, long sizeBytes, String contentType);

    /** @throws BlobNotFoundException when the key is unknown. Never returns null. */
    InputStream open(String storageKey);

    boolean exists(String storageKey);
}
