package co.ara.onboarding.notification;

public enum NotificationType { ESCALATION, TASK_ASSIGNED, TASK_OVERDUE, NEW_CUSTOMER, MILESTONE_COMPLETED,
    STAGE_CHANGED, DOCUMENT_REQUESTED, DOCUMENT_UPLOADED, DOCUMENT_DECIDED, AGREEMENT_STATUS, NEW_COMMENT,
    WORKFLOW_PUBLISHED, RISK_CHANGED, DEADLINE_APPROACHING, EXPIRY_RENEWAL }
