/**
 * Generates src/components/icons/index.tsx from the design system's icon registry.
 *
 * Generated, never hand-written. Every icon is a single path precisely so the data
 * can live in a registry, and hand-copying 56 paths is how the set drifts out of
 * sync with the source of truth in docs/uispecs/design/03-icons/.
 *
 * Re-run with: npm run generate:icons
 */
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const registryPath = resolve(here, "../../docs/uispecs/design/03-icons/icons.json");
const outputPath = resolve(here, "../src/components/icons/index.tsx");

const registry = JSON.parse(readFileSync(registryPath, "utf8"));
const { grid, strokeWidth } = registry.$meta;

const pascal = (name) =>
  name.split(/[-_]/).map((part) => part[0].toUpperCase() + part.slice(1)).join("");

const entries = Object.entries(registry.icons);

const body = entries
  .map(([name, icon]) => {
    const comment = icon.description ? `/** ${icon.description} */\n` : "";
    return `${comment}export const ${pascal(name)}Icon = (props: IconProps) => (
  <Icon {...props} d="${icon.path}" />
);`;
  })
  .join("\n\n");

const file = `// GENERATED by scripts/generate-icons.mjs from
// docs/uispecs/design/03-icons/icons.json — ${entries.length} icons. Do not edit.
//
// Every icon is decorative unless it is the only content of a control: pass a
// \`title\` when the icon IS the label, and nothing otherwise. With no title the
// svg is aria-hidden, so a screen reader never announces it twice alongside
// adjacent text.
import type { SVGProps } from "react";

export type IconProps = Omit<SVGProps<SVGSVGElement>, "children"> & {
  /** Accessible name. Omit for decorative icons sitting next to a text label. */
  title?: string;
  /** Pixel size; ${grid}px grid, so 16 and 24 land on whole pixels. */
  size?: number;
};

function Icon({ d, title, size = 16, ...props }: IconProps & { d: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 ${grid} ${grid}"
      width={size}
      height={size}
      fill="none"
      stroke="currentColor"
      strokeWidth={${strokeWidth}}
      strokeLinecap="round"
      strokeLinejoin="round"
      role={title ? "img" : undefined}
      aria-hidden={title ? undefined : true}
      focusable="false"
      {...props}
    >
      {title ? <title>{title}</title> : null}
      <path d={d} />
    </svg>
  );
}

${body}

/** Every icon by registry name, for data-driven use such as the nav array. */
export const ICONS: Record<string, string> = {
${entries.map(([name, icon]) => `  "${name}": "${icon.path}",`).join("\n")}
};
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, file, "utf8");
console.log(`Generated ${entries.length} icons -> ${outputPath}`);
