// GENERATED by scripts/generate-icons.mjs from
// docs/uispecs/design/03-icons/icons.json — 56 icons. Do not edit.
//
// Every icon is decorative unless it is the only content of a control: pass a
// `title` when the icon IS the label, and nothing otherwise. With no title the
// svg is aria-hidden, so a screen reader never announces it twice alongside
// adjacent text.
import type { SVGProps } from "react";

export type IconProps = Omit<SVGProps<SVGSVGElement>, "children"> & {
  /** Accessible name. Omit for decorative icons sitting next to a text label. */
  title?: string;
  /** Pixel size; 24px grid, so 16 and 24 land on whole pixels. */
  size?: number;
};

function Icon({ d, title, size = 16, ...props }: IconProps & { d: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="none"
      stroke="currentColor"
      strokeWidth={1.5}
      strokeLinecap="round"
      strokeLinejoin="round"
      role={title ? "img" : undefined}
      aria-hidden={title ? undefined : true}
      focusable="false"
      {...props}
    >
      {title ? <title>{title}</title> : null}
      <path d={d} />
    </svg>
  );
}

/** Dashboard / operational hub */
export const LayoutDashboardIcon = (props: IconProps) => (
  <Icon {...props} d="M4 5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1zM13 5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1zM13 12a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1zM4 14a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1z" />
);

/** Customers / accounts list */
export const UsersIcon = (props: IconProps) => (
  <Icon {...props} d="M15 20v-1.5a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4V20M12 7.5a3.5 3.5 0 1 1-7 0a3.5 3.5 0 0 1 7 0M17 14.2a4 4 0 0 1 5 3.8V20M16 4.3a3.5 3.5 0 0 1 0 6.8" />
);

/** Journey workspace / staged roadmap */
export const JourneyIcon = (props: IconProps) => (
  <Icon {...props} d="M5.5 7a2 2 0 1 0 0-4a2 2 0 0 0 0 4M5.5 14a2 2 0 1 0 0-4a2 2 0 0 0 0 4M5.5 21a2 2 0 1 0 0-4a2 2 0 0 0 0 4M5.5 7v3M5.5 14v3M10 5h10M10 12h7M10 19h8" />
);

/** Workflow builder / stage graph */
export const WorkflowIcon = (props: IconProps) => (
  <Icon {...props} d="M4 3.5h6v5H4zM14 15h6v5h-6zM7 8.5v7a2 2 0 0 0 2 2h5" />
);

/** Reports & analytics */
export const ChartColumnIcon = (props: IconProps) => (
  <Icon {...props} d="M4 4v15a1 1 0 0 0 1 1h15M8.5 16.5v-4M13 16.5v-7M17.5 16.5v-10" />
);

/** Customer portal / external view */
export const PortalWindowIcon = (props: IconProps) => (
  <Icon {...props} d="M3 6.5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2zM3 9.5h18M6 7h.01M8.5 7h.01" />
);

/** Design notes / edit */
export const PencilLineIcon = (props: IconProps) => (
  <Icon {...props} d="M4 20.5h16M15.2 4.8a2 2 0 0 1 2.8 2.8L8.4 17.2 4.5 18.5l1.3-3.9z" />
);

/** Global search */
export const SearchIcon = (props: IconProps) => (
  <Icon {...props} d="M20 20l-4.2-4.2M17 10.5a6.5 6.5 0 1 1-13 0a6.5 6.5 0 0 1 13 0" />
);

/** Create / add */
export const PlusIcon = (props: IconProps) => (
  <Icon {...props} d="M12 5v14M5 12h14" />
);

/** Close / remove */
export const XIcon = (props: IconProps) => (
  <Icon {...props} d="M6 6l12 12M18 6L6 18" />
);

/** Expand / collapse down */
export const ChevronDownIcon = (props: IconProps) => (
  <Icon {...props} d="M6 9.5l6 6l6-6" />
);

/** Collapse up / move up */
export const ChevronUpIcon = (props: IconProps) => (
  <Icon {...props} d="M6 14.5l6-6l6 6" />
);

/** Drill in */
export const ChevronRightIcon = (props: IconProps) => (
  <Icon {...props} d="M9.5 6l6 6l-6 6" />
);

/** Back */
export const ChevronLeftIcon = (props: IconProps) => (
  <Icon {...props} d="M14.5 6l-6 6l6 6" />
);

/** Transition / branch target */
export const ArrowRightIcon = (props: IconProps) => (
  <Icon {...props} d="M4 12h15M13 6l6 6l-6 6" />
);

/** Row overflow menu */
export const MoreHorizontalIcon = (props: IconProps) => (
  <Icon {...props} d="M6 12h.01M12 12h.01M18 12h.01" />
);

/** Filter list */
export const FilterIcon = (props: IconProps) => (
  <Icon {...props} d="M4 5.5h16l-6.2 7.4v5.9l-3.6-1.8v-4.1z" />
);

/** Drag handle / reorder */
export const GripVerticalIcon = (props: IconProps) => (
  <Icon {...props} d="M9 6h.01M9 12h.01M9 18h.01M15 6h.01M15 12h.01M15 18h.01" />
);

/** Done / completed */
export const CheckIcon = (props: IconProps) => (
  <Icon {...props} d="M4.5 12.5l5 5L20 6" />
);

/** Milestone complete / approved */
export const CheckCircleIcon = (props: IconProps) => (
  <Icon {...props} d="M9 12.2l2.2 2.2 4.8-5.4M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0" />
);

/** At risk / SLA breach */
export const AlertTriangleIcon = (props: IconProps) => (
  <Icon {...props} d="M12 4.5l8.5 14.5H3.5zM12 10v3.5M12 16.2h.01" />
);

/** Blocked */
export const AlertCircleIcon = (props: IconProps) => (
  <Icon {...props} d="M12 7.5v5M12 16h.01M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0" />
);

/** Due / pending */
export const ClockIcon = (props: IconProps) => (
  <Icon {...props} d="M12 7.5V12l3 2M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0" />
);

/** Waiting on third party */
export const PauseCircleIcon = (props: IconProps) => (
  <Icon {...props} d="M10 9.5v5M14 9.5v5M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0" />
);

/** Cancelled */
export const XCircleIcon = (props: IconProps) => (
  <Icon {...props} d="M14.8 9.2l-5.6 5.6M9.2 9.2l5.6 5.6M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0" />
);

/** Bare alert stroke, for use inside a coloured status circle */
export const ExclamationIcon = (props: IconProps) => (
  <Icon {...props} d="M12 6v7M12 17.2h.01" />
);

/** Document */
export const FileTextIcon = (props: IconProps) => (
  <Icon {...props} d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8zM14 3v5h5M8.5 13h7M8.5 16.5h4.5" />
);

/** Agreement / signature required */
export const FileSignatureIcon = (props: IconProps) => (
  <Icon {...props} d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8zM14 3v5h5M8.5 16.5c1.3-2 2.6-2 3.9 0s2.6 2 3.9 0" />
);

/** Document category */
export const FolderIcon = (props: IconProps) => (
  <Icon {...props} d="M4 7.5a2 2 0 0 1 2-2h3.2l2 2.5H18a2 2 0 0 1 2 2v8.5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z" />
);

/** Download / export */
export const DownloadIcon = (props: IconProps) => (
  <Icon {...props} d="M12 4v11M7.5 11l4.5 4.5 4.5-4.5M4.5 20h15" />
);

/** Upload requested document */
export const UploadIcon = (props: IconProps) => (
  <Icon {...props} d="M12 20V8.5M7.5 13l4.5-4.5 4.5 4.5M4.5 4.5h15" />
);

/** Attachment */
export const PaperclipIcon = (props: IconProps) => (
  <Icon {...props} d="M18.5 11.5l-7.6 7.6a4.2 4.2 0 0 1-5.9-5.9l7.4-7.4a2.8 2.8 0 0 1 4 4l-7.4 7.4a1.4 1.4 0 0 1-2-2l6.8-6.8" />
);

/** Visible to / portal scope */
export const EyeIcon = (props: IconProps) => (
  <Icon {...props} d="M2.5 12s3.5-6.5 9.5-6.5S21.5 12 21.5 12s-3.5 6.5-9.5 6.5S2.5 12 2.5 12zM14.5 12a2.5 2.5 0 1 1-5 0a2.5 2.5 0 0 1 5 0" />
);

/** Internal only / encrypted */
export const LockIcon = (props: IconProps) => (
  <Icon {...props} d="M6.5 10.5h11a1.5 1.5 0 0 1 1.5 1.5v7a1.5 1.5 0 0 1-1.5 1.5h-11A1.5 1.5 0 0 1 5 19v-7a1.5 1.5 0 0 1 1.5-1.5zM8.5 10.5V8a3.5 3.5 0 0 1 7 0v2.5" />
);

/** Concurrent cases */
export const LayersIcon = (props: IconProps) => (
  <Icon {...props} d="M12 3.5l8.5 4.5-8.5 4.5L3.5 8zM3.5 12.5l8.5 4.5 8.5-4.5M3.5 16.5l8.5 4.5 8.5-4.5" />
);

/** Compliance / KYC cleared */
export const ShieldCheckIcon = (props: IconProps) => (
  <Icon {...props} d="M12 3l7.5 2.8v6.4c0 4.4-3.1 7-7.5 8.8-4.4-1.8-7.5-4.4-7.5-8.8V5.8zM8.8 12.2l2.4 2.4 4-4.6" />
);

/** Legal team */
export const ScaleIcon = (props: IconProps) => (
  <Icon {...props} d="M12 4v16M7 20h10M4.5 8.5h15M7 8.5L4 14.5h6zM17 8.5l-3 6h6z" />
);

/** Technical setup / configuration */
export const SlidersIcon = (props: IconProps) => (
  <Icon {...props} d="M5 7h9M18 7h1M5 12h3M12 12h7M5 17h7M16 17h3M16 5v4M10 10v4M14 15v4" />
);

/** Training handover */
export const GraduationCapIcon = (props: IconProps) => (
  <Icon {...props} d="M12 5.5L21.5 9.5 12 13.5 2.5 9.5zM6.5 11.2v4.3c0 1.8 2.5 3 5.5 3s5.5-1.2 5.5-3v-4.3" />
);

/** Go live / milestone marker */
export const FlagIcon = (props: IconProps) => (
  <Icon {...props} d="M6 20V4.5h12l-2.5 4 2.5 4H6" />
);

/** Verification stage */
export const ClipboardCheckIcon = (props: IconProps) => (
  <Icon {...props} d="M9 4.5H7a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-12a2 2 0 0 0-2-2h-2M9 3h6a1 1 0 0 1 1 1v1.5a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1zM9 13.5l2 2 4-4.5" />
);

/** Sales approval / assigned owner */
export const UserCheckIcon = (props: IconProps) => (
  <Icon {...props} d="M15 20v-1.5a4 4 0 0 0-4-4H6.5a4 4 0 0 0-4 4V20M13 7.5a4 4 0 1 1-8 0a4 4 0 0 1 8 0M16.5 12.2l1.8 1.8 3.4-4" />
);

/** Customer company */
export const BuildingIcon = (props: IconProps) => (
  <Icon {...props} d="M4.5 20.5V6a1.5 1.5 0 0 1 1.5-1.5h7A1.5 1.5 0 0 1 14.5 6v14.5M14.5 10.5H18a1.5 1.5 0 0 1 1.5 1.5v8.5M3 20.5h18M7.5 8h4M7.5 11.5h4M7.5 15h4" />
);

/** Finance / invoicing */
export const CreditCardIcon = (props: IconProps) => (
  <Icon {...props} d="M4 8.5a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v7a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2zM4 11h16M7.5 14.5h3" />
);

/** Auto-advance / automated transition */
export const RefreshCwIcon = (props: IconProps) => (
  <Icon {...props} d="M20 5.5v5h-5M4 18.5v-5h5M4.6 10.2a8 8 0 0 1 13.2-3l2.2 2.3M19.4 13.8a8 8 0 0 1-13.2 3L4 13.5" />
);

/** Notifications */
export const BellIcon = (props: IconProps) => (
  <Icon {...props} d="M18.5 15.5V10a6.5 6.5 0 1 0-13 0v5.5L4 18h16zM9.5 18a2.5 2.5 0 0 0 5 0" />
);

/** Upcoming activity / due date */
export const CalendarIcon = (props: IconProps) => (
  <Icon {...props} d="M6.5 5h11a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2h-11a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2zM4.5 10h15M8.5 3v4M15.5 3v4" />
);

/** Comments */
export const MessageSquareIcon = (props: IconProps) => (
  <Icon {...props} d="M20.5 15.5a2 2 0 0 1-2 2H8l-4 3.5v-15a2 2 0 0 1 2-2h12.5a2 2 0 0 1 2 2z" />
);

/** Mention a teammate */
export const AtSignIcon = (props: IconProps) => (
  <Icon {...props} d="M12 16.5a4.5 4.5 0 1 0 0-9a4.5 4.5 0 0 0 0 9M16.5 7.5V13a3.5 3.5 0 0 0 3.5 3.5c1 0 1.5-2 1.5-4.5A9.5 9.5 0 1 0 15 20.7" />
);

/** Dependency */
export const LinkIcon = (props: IconProps) => (
  <Icon {...props} d="M10 13.5a4 4 0 0 0 6 .5l3-3a4 4 0 0 0-5.7-5.7L11.5 7M14 10.5a4 4 0 0 0-6-.5l-3 3a4 4 0 0 0 5.7 5.7L12.5 17" />
);

/** Activity timeline / audit */
export const HistoryIcon = (props: IconProps) => (
  <Icon {...props} d="M4 5.5v5h5M4.3 13.2a8 8 0 1 0 1-6.2M12 8.5V12l3 1.8" />
);

/** Open portal / external link */
export const ExternalLinkIcon = (props: IconProps) => (
  <Icon {...props} d="M13.5 4.5H19a.5.5 0 0 1 .5.5v5.5M19.5 4.5L12 12M17 14v4.5a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V8.5a1 1 0 0 1 1-1h4.5" />
);

/** Positive delta */
export const TrendingUpIcon = (props: IconProps) => (
  <Icon {...props} d="M4 16.5l5.5-5.5 3.5 3.5L20 7.5M14.5 7.5h5.5V13" />
);

/** Negative delta */
export const TrendingDownIcon = (props: IconProps) => (
  <Icon {...props} d="M4 7.5l5.5 5.5 3.5-3.5L20 16.5M14.5 16.5h5.5V11" />
);

/** Task complete */
export const CheckSquareIcon = (props: IconProps) => (
  <Icon {...props} d="M8.5 12.2l2.4 2.4 4.6-5.2M5.5 4.5h13a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-13a1 1 0 0 1-1-1v-13a1 1 0 0 1 1-1z" />
);

/** Task open */
export const SquareIcon = (props: IconProps) => (
  <Icon {...props} d="M5.5 4.5h13a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-13a1 1 0 0 1-1-1v-13a1 1 0 0 1 1-1z" />
);

/** Every icon by registry name, for data-driven use such as the nav array. */
export const ICONS: Record<string, string> = {
  "layout-dashboard": "M4 5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1zM13 5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1zM13 12a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1zM4 14a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1z",
  "users": "M15 20v-1.5a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4V20M12 7.5a3.5 3.5 0 1 1-7 0a3.5 3.5 0 0 1 7 0M17 14.2a4 4 0 0 1 5 3.8V20M16 4.3a3.5 3.5 0 0 1 0 6.8",
  "journey": "M5.5 7a2 2 0 1 0 0-4a2 2 0 0 0 0 4M5.5 14a2 2 0 1 0 0-4a2 2 0 0 0 0 4M5.5 21a2 2 0 1 0 0-4a2 2 0 0 0 0 4M5.5 7v3M5.5 14v3M10 5h10M10 12h7M10 19h8",
  "workflow": "M4 3.5h6v5H4zM14 15h6v5h-6zM7 8.5v7a2 2 0 0 0 2 2h5",
  "chart-column": "M4 4v15a1 1 0 0 0 1 1h15M8.5 16.5v-4M13 16.5v-7M17.5 16.5v-10",
  "portal-window": "M3 6.5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2zM3 9.5h18M6 7h.01M8.5 7h.01",
  "pencil-line": "M4 20.5h16M15.2 4.8a2 2 0 0 1 2.8 2.8L8.4 17.2 4.5 18.5l1.3-3.9z",
  "search": "M20 20l-4.2-4.2M17 10.5a6.5 6.5 0 1 1-13 0a6.5 6.5 0 0 1 13 0",
  "plus": "M12 5v14M5 12h14",
  "x": "M6 6l12 12M18 6L6 18",
  "chevron-down": "M6 9.5l6 6l6-6",
  "chevron-up": "M6 14.5l6-6l6 6",
  "chevron-right": "M9.5 6l6 6l-6 6",
  "chevron-left": "M14.5 6l-6 6l6 6",
  "arrow-right": "M4 12h15M13 6l6 6l-6 6",
  "more-horizontal": "M6 12h.01M12 12h.01M18 12h.01",
  "filter": "M4 5.5h16l-6.2 7.4v5.9l-3.6-1.8v-4.1z",
  "grip-vertical": "M9 6h.01M9 12h.01M9 18h.01M15 6h.01M15 12h.01M15 18h.01",
  "check": "M4.5 12.5l5 5L20 6",
  "check-circle": "M9 12.2l2.2 2.2 4.8-5.4M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0",
  "alert-triangle": "M12 4.5l8.5 14.5H3.5zM12 10v3.5M12 16.2h.01",
  "alert-circle": "M12 7.5v5M12 16h.01M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0",
  "clock": "M12 7.5V12l3 2M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0",
  "pause-circle": "M10 9.5v5M14 9.5v5M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0",
  "x-circle": "M14.8 9.2l-5.6 5.6M9.2 9.2l5.6 5.6M21 12a9 9 0 1 1-18 0a9 9 0 0 1 18 0",
  "exclamation": "M12 6v7M12 17.2h.01",
  "file-text": "M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8zM14 3v5h5M8.5 13h7M8.5 16.5h4.5",
  "file-signature": "M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8zM14 3v5h5M8.5 16.5c1.3-2 2.6-2 3.9 0s2.6 2 3.9 0",
  "folder": "M4 7.5a2 2 0 0 1 2-2h3.2l2 2.5H18a2 2 0 0 1 2 2v8.5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z",
  "download": "M12 4v11M7.5 11l4.5 4.5 4.5-4.5M4.5 20h15",
  "upload": "M12 20V8.5M7.5 13l4.5-4.5 4.5 4.5M4.5 4.5h15",
  "paperclip": "M18.5 11.5l-7.6 7.6a4.2 4.2 0 0 1-5.9-5.9l7.4-7.4a2.8 2.8 0 0 1 4 4l-7.4 7.4a1.4 1.4 0 0 1-2-2l6.8-6.8",
  "eye": "M2.5 12s3.5-6.5 9.5-6.5S21.5 12 21.5 12s-3.5 6.5-9.5 6.5S2.5 12 2.5 12zM14.5 12a2.5 2.5 0 1 1-5 0a2.5 2.5 0 0 1 5 0",
  "lock": "M6.5 10.5h11a1.5 1.5 0 0 1 1.5 1.5v7a1.5 1.5 0 0 1-1.5 1.5h-11A1.5 1.5 0 0 1 5 19v-7a1.5 1.5 0 0 1 1.5-1.5zM8.5 10.5V8a3.5 3.5 0 0 1 7 0v2.5",
  "layers": "M12 3.5l8.5 4.5-8.5 4.5L3.5 8zM3.5 12.5l8.5 4.5 8.5-4.5M3.5 16.5l8.5 4.5 8.5-4.5",
  "shield-check": "M12 3l7.5 2.8v6.4c0 4.4-3.1 7-7.5 8.8-4.4-1.8-7.5-4.4-7.5-8.8V5.8zM8.8 12.2l2.4 2.4 4-4.6",
  "scale": "M12 4v16M7 20h10M4.5 8.5h15M7 8.5L4 14.5h6zM17 8.5l-3 6h6z",
  "sliders": "M5 7h9M18 7h1M5 12h3M12 12h7M5 17h7M16 17h3M16 5v4M10 10v4M14 15v4",
  "graduation-cap": "M12 5.5L21.5 9.5 12 13.5 2.5 9.5zM6.5 11.2v4.3c0 1.8 2.5 3 5.5 3s5.5-1.2 5.5-3v-4.3",
  "flag": "M6 20V4.5h12l-2.5 4 2.5 4H6",
  "clipboard-check": "M9 4.5H7a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-12a2 2 0 0 0-2-2h-2M9 3h6a1 1 0 0 1 1 1v1.5a1 1 0 0 1-1 1H9a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1zM9 13.5l2 2 4-4.5",
  "user-check": "M15 20v-1.5a4 4 0 0 0-4-4H6.5a4 4 0 0 0-4 4V20M13 7.5a4 4 0 1 1-8 0a4 4 0 0 1 8 0M16.5 12.2l1.8 1.8 3.4-4",
  "building": "M4.5 20.5V6a1.5 1.5 0 0 1 1.5-1.5h7A1.5 1.5 0 0 1 14.5 6v14.5M14.5 10.5H18a1.5 1.5 0 0 1 1.5 1.5v8.5M3 20.5h18M7.5 8h4M7.5 11.5h4M7.5 15h4",
  "credit-card": "M4 8.5a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v7a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2zM4 11h16M7.5 14.5h3",
  "refresh-cw": "M20 5.5v5h-5M4 18.5v-5h5M4.6 10.2a8 8 0 0 1 13.2-3l2.2 2.3M19.4 13.8a8 8 0 0 1-13.2 3L4 13.5",
  "bell": "M18.5 15.5V10a6.5 6.5 0 1 0-13 0v5.5L4 18h16zM9.5 18a2.5 2.5 0 0 0 5 0",
  "calendar": "M6.5 5h11a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2h-11a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2zM4.5 10h15M8.5 3v4M15.5 3v4",
  "message-square": "M20.5 15.5a2 2 0 0 1-2 2H8l-4 3.5v-15a2 2 0 0 1 2-2h12.5a2 2 0 0 1 2 2z",
  "at-sign": "M12 16.5a4.5 4.5 0 1 0 0-9a4.5 4.5 0 0 0 0 9M16.5 7.5V13a3.5 3.5 0 0 0 3.5 3.5c1 0 1.5-2 1.5-4.5A9.5 9.5 0 1 0 15 20.7",
  "link": "M10 13.5a4 4 0 0 0 6 .5l3-3a4 4 0 0 0-5.7-5.7L11.5 7M14 10.5a4 4 0 0 0-6-.5l-3 3a4 4 0 0 0 5.7 5.7L12.5 17",
  "history": "M4 5.5v5h5M4.3 13.2a8 8 0 1 0 1-6.2M12 8.5V12l3 1.8",
  "external-link": "M13.5 4.5H19a.5.5 0 0 1 .5.5v5.5M19.5 4.5L12 12M17 14v4.5a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V8.5a1 1 0 0 1 1-1h4.5",
  "trending-up": "M4 16.5l5.5-5.5 3.5 3.5L20 7.5M14.5 7.5h5.5V13",
  "trending-down": "M4 7.5l5.5 5.5 3.5-3.5L20 16.5M14.5 16.5h5.5V11",
  "check-square": "M8.5 12.2l2.4 2.4 4.6-5.2M5.5 4.5h13a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-13a1 1 0 0 1-1-1v-13a1 1 0 0 1 1-1z",
  "square": "M5.5 4.5h13a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-13a1 1 0 0 1-1-1v-13a1 1 0 0 1 1-1z",
};
